### ISSUE TITLE
`hms::as.hms` returns `NA` if not provided seconds precision

### ISSUE THREAD

**Issue by ellisvalentiner** [ellisvalentiner/lubridateExtras#9]
The default behavior in hms:

```r
> hms::as.hms("01:02")
NA
```

but it would be convenient if instead

```r
> hms::as.hms("01:02")
01:02:00
```

particularly because then

```
> lubridateExtras::hms("2017-10-23 16:11")
16:11:00
```

**Comment by j450h1** [comment]
Looks like this change was implemented in a different way and this issue can now be closed.



    lubridateExtras::hms("2017-10-23 16:11")
    #> 16:11:00

<sup>Created on 2018-10-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ellisvalentiner** [comment]
Thanks for noticing. I don't remember fixing this issue.
